In [7]:
import pandas as pd

In [8]:
df1 = pd.read_excel("C:\\Users\\k_pow\\OneDrive\\Documents\\Capstone\\Supercloud_transfer\\indiaHS2.xlsx")

In [9]:
df1.head()

,HS CODE,PRODUCT DESCRIPTION,CONSIGNEE,CONSIGNEE ADDRESS,COUNTRY OF ORIGIN,ARRIVAL DATE,QUANTITY,UNIT,UNIT PRICE IN USD,CURRENCY,PRICE IN INR,TOTAL PRICE IN INR,INDIAN PORT,TRANSPORTATION TYPE,BILL OF LADING
0,85444220,PWR-CORD-IND-B POWER CORD FOR INDIA 2M 10A,CISCO COMMERCE INDIA PRIVATE LIMITED,,CHINA,2022-11-30,1.0,NOS,18.45,INR,1523.57,1523.57,Bombay Air,AIR,3536352
1,84713010,509X4EC HP ELITEBOOK X360 1030 G8 NOTEBOOK PC ...,HP INDIA SALES PRIVATE LIMITED,,CHINA,2022-11-30,41.0,NOS,864.32,USD,71392.97,2927111.90,Bombay Air,AIR,3536560
2,85369090,E24 00909 XX16 A CONN 040 W/B 16P HEADER ASSY ...,MINDA INSTRUMENTS LIMITED,,CHINA,2022-11-30,810.0,NOS,0.43,USD,35.36,28643.40,Bombay Air,AIR,3537063
3,85369090,E24 00909 XX16 A CONN 040 W/B 16P HEADER ASSY ...,MINDA INSTRUMENTS LIMITED,,CHINA,2022-11-30,810.0,NOS,0.43,USD,35.36,28643.40,Bombay Air,AIR,3537063
4,85411000,"E04-00540-22W1-B CPL# 224 DIODES, ZENER",MINDA INSTRUMENTS LIMITED,,MALAYSIA,2022-11-30,15000.0,NOS,0.06,USD,4.92,73832.31,Bombay Air,AIR,3537102

In [10]:
df2 = pd.read_csv("C:\\Users\\k_pow\\OneDrive\\Documents\\Capstone\\Webscraping\\india scrape\\IndiaHS3.csv")

C:\Users\k_pow\AppData\Local\Temp\ipykernel_7264\1806903481.py:1: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv("C:\\Users\\k_pow\\OneDrive\\Documents\\Capstone\\Webscraping\\india scrape\\IndiaHS3.csv")

In [11]:
df2.head()

,Unnamed: 0,number,arrivalDate,bank,consignee,consigneeAddress,consigneeEmail,consigneeFax,consigneePhone,contact1,...,insuranceUsd,productDescription,quantity,shipper,shipperAddress,unit,unitPriceEuro,unitPriceUsd,entryId,zipCode
0,0,1,2024-12-31T00:00:00.000Z,NaN,NORTH EAST SPIRITS,"Central Warehouse, EPIP Complex ,┬á Amingaon, ...",NaN,NaN,NaN,NaN,...,NaN,JACK DANIEL'S OLD NO 7 TENNESSEE (12 X 750ML)(...,90.0,BROWN-FORMAN BEVERAGES WORLDWIDE,"P.O. BOX 1080 LOUISVILLE, KY 40210- 1080 0 UNI...",LTR,0,7.07,90809840,NaN
1,1,2,2024-12-31T00:00:00.000Z,AXIS BANK LTD.FORTMUMBAI-1 A/C Type:1 CA A/C ...,ALLIED BLENDERS AND DISTILLERS LIMITED,"394-C, LAMINGTON CHAMBERS, LAMINGTON ROAD, MUM...",info@abdindia.com,NaN,022-67779777 fax no. 4930986,1. : UTPAL KUMAR GANGULI S GANGULI 14 SOUTHEND...,...,NaN,BVM03350000 03YO BLENDED MALT SCOTCH WHISKY[BU...,1639.3,INVER HOUSE DISTILLERS LTD.,NaN,LTR,0,5.16,90809841,NaN
2,2,3,2024-12-31T00:00:00.000Z,AXIS BANK LTD.FORTMUMBAI-1 A/C Type:1 CA A/C ...,ALLIED BLENDERS AND DISTILLERS LIMITED,"394-C, LAMINGTON CHAMBERS, LAMINGTON ROAD, MUM...",info@abdindia.com,NaN,022-67779777 fax no. 4930986,1. : UTPAL KUMAR GANGULI S GANGULI 14 SOUTHEND...,...,NaN,BVM032700 03YO PEATED MALT SCOTCH WHISKY[BULK ...,366.6,INVER HOUSE DISTILLERS LTD.,NaN,LTR,0,5.32,90809842,NaN
3,3,4,2024-12-31T00:00:00.000Z,AXIS BANK LTD.FORTMUMBAI-1 A/C Type:1 CA A/C ...,ALLIED BLENDERS AND DISTILLERS LIMITED,"394-C, LAMINGTON CHAMBERS, LAMINGTON ROAD, MUM...",info@abdindia.com,NaN,022-67779777 fax no. 4930986,1. : UTPAL KUMAR GANGULI S GANGULI 14 SOUTHEND...,...,NaN,BVM03350000 03YO BLENDED MALT SCOTCH WHISKY [B...,6400.5,INVER HOUSE DISTILLERS LTD.,NaN,LTR,0,5.20,90809843,NaN
4,4,5,2024-12-31T00:00:00.000Z,JHANDEWALAN EXTN. BRANCHND-110055 A/C Type:1 ...,BRINDCO SALES PRIVATE LIMITED,S-53 OKHLA INDL. AREA-II N/A NEW DELHI,N?A,NaN,6.91871E+13,1. : BRINDER PAL SINGH LATE SH.PRATAP SINGH DH...,...,NaN,JACK DANIEL'S OLD NO 7 TENNESSEE (12 X 750ML)(...,27.0,BROWN-FORMAN BEVERAGES WORLDWIDE,"P.O. BOX 1080 LOUISVILLE, KY 40210- 1080 UNITE...",LTR,0,7.07,90809844,NaN

In [12]:
# Rename columns in df2 and df3 to match df1's format
column_mapping = {
    'hsCode': 'HS CODE',
    'productDescription': 'PRODUCT DESCRIPTION',
    'consignee': 'CONSIGNEE',
    'consigneeAddress': 'CONSIGNEE ADDRESS',
    'countryOfOrigin': 'COUNTRY OF ORIGIN',
    'arrivalDate': 'ARRIVAL DATE',
    'quantity': 'QUANTITY',
    'unit': 'UNIT',
    'unitPriceUsd': 'UNIT PRICE IN USD'
}

# Apply the mapping to df2 and df3
df2_renamed = df2.rename(columns=column_mapping)
#df3_renamed = df3.rename(columns=column_mapping)

# Create missing columns with NaN values in df2 and df3
for col in df1.columns:
    if col not in df2_renamed.columns:
        df2_renamed[col] = pd.NA
    # if col not in df3_renamed.columns:
    #     df3_renamed[col] = pd.NA

# Keep only the columns that exist in df1
columns_to_keep = df1.columns

df2_filtered = df2_renamed[columns_to_keep]
# df3_filtered = df3_renamed[columns_to_keep]

# Combine all dataframes
combined_df = pd.concat([df1, df2_filtered], ignore_index=True)

C:\Users\k_pow\AppData\Local\Temp\ipykernel_7264\4186707081.py:32: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_df = pd.concat([df1, df2_filtered], ignore_index=True)

In [13]:
combined_df

,HS CODE,PRODUCT DESCRIPTION,CONSIGNEE,CONSIGNEE ADDRESS,COUNTRY OF ORIGIN,ARRIVAL DATE,QUANTITY,UNIT,UNIT PRICE IN USD,CURRENCY,PRICE IN INR,TOTAL PRICE IN INR,INDIAN PORT,TRANSPORTATION TYPE,BILL OF LADING
0,85444220,PWR-CORD-IND-B POWER CORD FOR INDIA 2M 10A,CISCO COMMERCE INDIA PRIVATE LIMITED,,CHINA,2022-11-30,1.0,NOS,18.45,INR,1523.57,1523.57,Bombay Air,AIR,3536352
1,84713010,509X4EC HP ELITEBOOK X360 1030 G8 NOTEBOOK PC ...,HP INDIA SALES PRIVATE LIMITED,,CHINA,2022-11-30,41.0,NOS,864.32,USD,71392.97,2927111.90,Bombay Air,AIR,3536560
2,85369090,E24 00909 XX16 A CONN 040 W/B 16P HEADER ASSY ...,MINDA INSTRUMENTS LIMITED,,CHINA,2022-11-30,810.0,NOS,0.43,USD,35.36,28643.40,Bombay Air,AIR,3537063
3,85369090,E24 00909 XX16 A CONN 040 W/B 16P HEADER ASSY ...,MINDA INSTRUMENTS LIMITED,,CHINA,2022-11-30,810.0,NOS,0.43,USD,35.36,28643.40,Bombay Air,AIR,3537063
4,85411000,"E04-00540-22W1-B CPL# 224 DIODES, ZENER",MINDA INSTRUMENTS LIMITED,,MALAYSIA,2022-11-30,15000.0,NOS,0.06,USD,4.92,73832.31,Bombay Air,AIR,3537102
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109995,87082900,K6ENOOTX7AC MOULDING K6ENOOTX7AC MOULDING,FCA INDIA AUTOMOBILES PRIVATE LIMITED,"BENEFICE, 2ND FLOOR, MATHURADAS MILL COMPOUND,...",UNITED STATES,2024-12-26T00:00:00.000Z,2.0,PCS,36.80,NaN,NaN,NaN,NaN,NaN,<NA>
109996,87082900,K6NH70RXFAB PROTECTION K6NH70RXFAB PROTECTION,FCA INDIA AUTOMOBILES PRIVATE LIMITED,"BENEFICE, 2ND FLOOR, MATHURADAS MILL COMPOUND,...",UNITED STATES,2024-12-26T00:00:00.000Z,1.0,PCS,34.27,NaN,NaN,NaN,NaN,NaN,<NA>
109997,87082900,K6NH70RXFAB PROTECTION K6NH70RXFAB PROTECTION,FCA INDIA AUTOMOBILES PRIVATE LIMITED,"BENEFICE, 2ND FLOOR, MATHURADAS MILL COMPOUND,...",UNITED STATES,2024-12-26T00:00:00.000Z,1.0,PCS,34.27,NaN,NaN,NaN,NaN,NaN,<NA>
109998,87082900,K6NH70RXFAB PROTECTION K6NH70RXFAB PROTECTION,FCA INDIA AUTOMOBILES PRIVATE LIMITED,"BENEFICE, 2ND FLOOR, MATHURADAS MILL COMPOUND,...",UNITED STATES,2024-12-26T00:00:00.000Z,5.0,PCS,34.27,NaN,NaN,NaN,NaN,NaN,<NA>
109999,87082900,K6WQ68TZZAA GRILLE K6WQ68TZZAA GRILLE,FCA INDIA AUTOMOBILES PRIVATE LIMITED,"BENEFICE, 2ND FLOOR, MATHURADAS MILL COMPOUND,...",MEXICO,2024-12-26T00:00:00.000Z,14.0,PCS,65.72,NaN,NaN,NaN,NaN,NaN,<NA>

In [14]:
# Save to CSV
combined_df.to_csv('combined_data_2.csv', index=False)

In [15]:
combined_df.shape

(110000, 15)